"""schema initiale

Revision ID: 594bce594adf
Revises:
Create Date: 2026-08-16 22:15:47.406977

Lot 1.1 (correctif C3, AUDIT_DATALAB_2026-08-16.md) — première révision
Alembic du projet, autogénérée depuis `Base.metadata` (les 22 tables
existantes) contre une base SQLite vierge. Remplace `_add_column_if_missing`
(migration additive maison, gelée — voir `api/core/database.py`).

Sur une base DÉJÀ EN SERVICE (les 22 tables existent déjà, créées par
l'ancien mécanisme) : `init_db()` détecte ce cas et exécute
`alembic stamp head` plutôt que `upgrade head` — cette révision n'est
JAMAIS rejouée sur une base existante (elle échouerait, les tables étant
déjà là). Testé dans `tests/test_alembic_migration.py` avec de vraies
données préexistantes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594bce594adf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('columns_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_organization_id'), ['organization_id'], unique=False)

    op.create_table('vision_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('structure_type', sa.String(length=20), nullable=False),
    sa.Column('storage_dir', sa.String(length=500), nullable=False),
    sa.Column('n_images', sa.Integer(), nullable=False),
    sa.Column('n_classes', sa.Integer(), nullable=True),
    sa.Column('class_distribution_json', sa.Text(), nullable=True),
    sa.Column('validation_report_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_datasets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_datasets_organization_id'), ['organization_id'], unique=False)

    op.create_table('anomaly_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_jobs_status'), ['status'], unique=False)

    op.create_table('clustering_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clustering_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clustering_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clustering_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clustering_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clustering_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clustering_jobs_status'), ['status'], unique=False)

    op.create_table('dimensionality_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimensionality_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimensionality_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_jobs_status'), ['status'], unique=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('group_column', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('feature_engineering_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)

    op.create_table('vision_anomaly_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vision_dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_dataset_id'], ['vision_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_anomaly_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_anomaly_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_jobs_vision_dataset_id'), ['vision_dataset_id'], unique=False)

    op.create_table('vision_classification_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vision_dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_dataset_id'], ['vision_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_classification_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_classification_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_jobs_vision_dataset_id'), ['vision_dataset_id'], unique=False)

    op.create_table('anomaly_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_job_id', sa.Integer(), nullable=False),
    sa.Column('n_samples_total', sa.Integer(), nullable=False),
    sa.Column('n_samples_used', sa.Integer(), nullable=False),
    sa.Column('sampled', sa.Boolean(), nullable=False),
    sa.Column('n_anomalies_isolation_forest', sa.Integer(), nullable=False),
    sa.Column('n_anomalies_lof', sa.Integer(), nullable=False),
    sa.Column('n_anomalies_consensus', sa.Integer(), nullable=False),
    sa.Column('anomaly_rate_isolation_forest', sa.Float(), nullable=False),
    sa.Column('anomaly_rate_lof', sa.Float(), nullable=False),
    sa.Column('anomaly_rate_consensus', sa.Float(), nullable=False),
    sa.Column('score_histogram_json', sa.Text(), nullable=False),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_job_id'], ['anomaly_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_job_id')
    )
    with op.batch_alter_table('anomaly_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('anomaly_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_job_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('consensus_score', sa.Float(), nullable=False),
    sa.Column('score_isolation_forest', sa.Float(), nullable=False),
    sa.Column('score_lof', sa.Float(), nullable=False),
    sa.Column('is_anomaly_isolation_forest', sa.Boolean(), nullable=False),
    sa.Column('is_anomaly_lof', sa.Boolean(), nullable=False),
    sa.Column('agreement', sa.String(length=30), nullable=False),
    sa.Column('numeric_deviations_json', sa.Text(), nullable=False),
    sa.Column('categorical_flags_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_job_id'], ['anomaly_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_observations_anomaly_job_id'), ['anomaly_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_observations_organization_id'), ['organization_id'], unique=False)

    op.create_table('cluster_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('clustering_job_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=30), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('n_clusters', sa.Integer(), nullable=False),
    sa.Column('silhouette', sa.Float(), nullable=True),
    sa.Column('davies_bouldin', sa.Float(), nullable=True),
    sa.Column('calinski_harabasz', sa.Float(), nullable=True),
    sa.Column('noise_ratio', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clustering_job_id'], ['clustering_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_candidates_clustering_job_id'), ['clustering_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_candidates_organization_id'), ['organization_id'], unique=False)

    op.create_table('cluster_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('clustering_job_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('n_clusters', sa.Integer(), nullable=False),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('profiles_json', sa.Text(), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clustering_job_id'], ['clustering_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clustering_job_id')
    )
    with op.batch_alter_table('cluster_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('dimensionality_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dimensionality_job_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('algorithm_id', sa.String(length=30), nullable=False),
    sa.Column('n_samples_total', sa.Integer(), nullable=False),
    sa.Column('n_samples_used', sa.Integer(), nullable=False),
    sa.Column('sampled', sa.Boolean(), nullable=False),
    sa.Column('trustworthiness_primary', sa.Float(), nullable=False),
    sa.Column('trustworthiness_pca', sa.Float(), nullable=False),
    sa.Column('variance_explained_json', sa.Text(), nullable=False),
    sa.Column('total_variance_explained', sa.Float(), nullable=False),
    sa.Column('loadings_json', sa.Text(), nullable=False),
    sa.Column('distance_fidelity_note', sa.Text(), nullable=False),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dimensionality_job_id'], ['dimensionality_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimensionality_job_id')
    )
    with op.batch_alter_table('dimensionality_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimensionality_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('dimensionality_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dimensionality_job_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dimensionality_job_id'], ['dimensionality_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimensionality_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimensionality_points_dimensionality_job_id'), ['dimensionality_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_points_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dimensionality_points_organization_id'), ['organization_id'], unique=False)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('feature_columns_json', sa.Text(), nullable=False),
    sa.Column('feature_schema_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('shap_summary_json', sa.Text(), nullable=True),
    sa.Column('cqr_json', sa.Text(), nullable=True),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('evaluation_json', sa.Text(), nullable=True),
    sa.Column('feature_engineering_json', sa.Text(), nullable=True),
    sa.Column('shap_beeswarm_json', sa.Text(), nullable=True),
    sa.Column('permutation_importance_json', sa.Text(), nullable=True),
    sa.Column('calibration_json', sa.Text(), nullable=True),
    sa.Column('learning_curve_json', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_job_id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('model_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=30), nullable=False),
    sa.Column('selection_score', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('fold_scores_json', sa.Text(), nullable=True),
    sa.Column('secondary_metric', sa.Float(), nullable=True),
    sa.Column('secondary_metric_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_candidates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_candidates_training_job_id'), ['training_job_id'], unique=False)

    op.create_table('vision_anomaly_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vision_anomaly_job_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_val', sa.Integer(), nullable=False),
    sa.Column('n_test', sa.Integer(), nullable=False),
    sa.Column('n_calibration', sa.Integer(), nullable=True),
    sa.Column('n_evaluation', sa.Integer(), nullable=True),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=False),
    sa.Column('test_accuracy', sa.Float(), nullable=False),
    sa.Column('test_precision', sa.Float(), nullable=False),
    sa.Column('test_recall', sa.Float(), nullable=False),
    sa.Column('test_f1', sa.Float(), nullable=False),
    sa.Column('confusion_matrix_json', sa.Text(), nullable=False),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_anomaly_job_id'], ['vision_anomaly_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vision_anomaly_job_id')
    )
    with op.batch_alter_table('vision_anomaly_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_anomaly_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('vision_classification_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vision_classification_job_id', sa.Integer(), nullable=False),
    sa.Column('backbone_id', sa.String(length=50), nullable=False),
    sa.Column('class_names_json', sa.Text(), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_val', sa.Integer(), nullable=False),
    sa.Column('n_test', sa.Integer(), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('test_accuracy', sa.Float(), nullable=False),
    sa.Column('test_precision_macro', sa.Float(), nullable=False),
    sa.Column('test_recall_macro', sa.Float(), nullable=False),
    sa.Column('test_f1_macro', sa.Float(), nullable=False),
    sa.Column('confusion_matrix_json', sa.Text(), nullable=False),
    sa.Column('examples_json', sa.Text(), nullable=False),
    sa.Column('model_card_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_classification_job_id'], ['vision_classification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vision_classification_job_id')
    )
    with op.batch_alter_table('vision_classification_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_classification_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_classification_models_organization_id'), ['organization_id'], unique=False)

    op.create_table('vision_anomaly_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vision_anomaly_model_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('defect_category', sa.String(length=100), nullable=False),
    sa.Column('true_label', sa.Integer(), nullable=False),
    sa.Column('predicted_label', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('heatmap_png', sa.Text(), nullable=False),
    sa.Column('mask_png', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_anomaly_model_id'], ['vision_anomaly_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_anomaly_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_anomaly_examples_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_examples_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_anomaly_examples_vision_anomaly_model_id'), ['vision_anomaly_model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vision_anomaly_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_examples_vision_anomaly_model_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_examples_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_examples_id'))

    op.drop_table('vision_anomaly_examples')
    with op.batch_alter_table('vision_classification_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_classification_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_models_id'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_models_created_at'))

    op.drop_table('vision_classification_models')
    with op.batch_alter_table('vision_anomaly_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_models_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_models_created_at'))

    op.drop_table('vision_anomaly_models')
    with op.batch_alter_table('model_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_candidates_training_job_id'))
        batch_op.drop_index(batch_op.f('ix_model_candidates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_model_candidates_id'))

    op.drop_table('model_candidates')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ml_models_id'))
        batch_op.drop_index(batch_op.f('ix_ml_models_created_at'))

    op.drop_table('ml_models')
    with op.batch_alter_table('dimensionality_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimensionality_points_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_points_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_points_dimensionality_job_id'))

    op.drop_table('dimensionality_points')
    with op.batch_alter_table('dimensionality_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimensionality_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_models_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_models_created_at'))

    op.drop_table('dimensionality_models')
    with op.batch_alter_table('cluster_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_models_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_models_created_at'))

    op.drop_table('cluster_models')
    with op.batch_alter_table('cluster_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_candidates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_candidates_clustering_job_id'))

    op.drop_table('cluster_candidates')
    with op.batch_alter_table('anomaly_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_observations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_observations_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_observations_anomaly_job_id'))

    op.drop_table('anomaly_observations')
    with op.batch_alter_table('anomaly_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_models_organization_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_models_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_models_created_at'))

    op.drop_table('anomaly_models')
    with op.batch_alter_table('vision_classification_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_classification_jobs_vision_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_vision_classification_jobs_created_at'))

    op.drop_table('vision_classification_jobs')
    with op.batch_alter_table('vision_anomaly_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_jobs_vision_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_vision_anomaly_jobs_created_at'))

    op.drop_table('vision_anomaly_jobs')
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_created_at'))

    op.drop_table('training_jobs')
    with op.batch_alter_table('dimensionality_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimensionality_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_jobs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dimensionality_jobs_created_at'))

    op.drop_table('dimensionality_jobs')
    with op.batch_alter_table('clustering_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clustering_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_clustering_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clustering_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_clustering_jobs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_clustering_jobs_created_at'))

    op.drop_table('clustering_jobs')
    with op.batch_alter_table('anomaly_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_anomaly_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_jobs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_jobs_created_at'))

    op.drop_table('anomaly_jobs')
    with op.batch_alter_table('vision_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_datasets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vision_datasets_id'))
        batch_op.drop_index(batch_op.f('ix_vision_datasets_created_at'))

    op.drop_table('vision_datasets')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_created_at'))

    op.drop_table('datasets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
