"""drift_logs_clustering_dimensionality_anomalies

Revision ID: ec93c856ac0b
Revises: 2c88481be342
Create Date: 2026-09-02 13:48:45.760451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec93c856ac0b'
down_revision: Union[str, Sequence[str], None] = '2c88481be342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_score_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_job_id', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_job_id'], ['anomaly_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_score_logs_anomaly_job_id'), 'anomaly_score_logs', ['anomaly_job_id'], unique=False)
    op.create_index(op.f('ix_anomaly_score_logs_created_at'), 'anomaly_score_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomaly_score_logs_id'), 'anomaly_score_logs', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_score_logs_organization_id'), 'anomaly_score_logs', ['organization_id'], unique=False)
    op.create_table('cluster_prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('clustering_job_id', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clustering_job_id'], ['clustering_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_prediction_logs_clustering_job_id'), 'cluster_prediction_logs', ['clustering_job_id'], unique=False)
    op.create_index(op.f('ix_cluster_prediction_logs_created_at'), 'cluster_prediction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_cluster_prediction_logs_id'), 'cluster_prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_cluster_prediction_logs_organization_id'), 'cluster_prediction_logs', ['organization_id'], unique=False)
    op.create_table('dimensionality_projection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dimensionality_job_id', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dimensionality_job_id'], ['dimensionality_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensionality_projection_logs_created_at'), 'dimensionality_projection_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dimensionality_projection_logs_dimensionality_job_id'), 'dimensionality_projection_logs', ['dimensionality_job_id'], unique=False)
    op.create_index(op.f('ix_dimensionality_projection_logs_id'), 'dimensionality_projection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dimensionality_projection_logs_organization_id'), 'dimensionality_projection_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimensionality_projection_logs_organization_id'), table_name='dimensionality_projection_logs')
    op.drop_index(op.f('ix_dimensionality_projection_logs_id'), table_name='dimensionality_projection_logs')
    op.drop_index(op.f('ix_dimensionality_projection_logs_dimensionality_job_id'), table_name='dimensionality_projection_logs')
    op.drop_index(op.f('ix_dimensionality_projection_logs_created_at'), table_name='dimensionality_projection_logs')
    op.drop_table('dimensionality_projection_logs')
    op.drop_index(op.f('ix_cluster_prediction_logs_organization_id'), table_name='cluster_prediction_logs')
    op.drop_index(op.f('ix_cluster_prediction_logs_id'), table_name='cluster_prediction_logs')
    op.drop_index(op.f('ix_cluster_prediction_logs_created_at'), table_name='cluster_prediction_logs')
    op.drop_index(op.f('ix_cluster_prediction_logs_clustering_job_id'), table_name='cluster_prediction_logs')
    op.drop_table('cluster_prediction_logs')
    op.drop_index(op.f('ix_anomaly_score_logs_organization_id'), table_name='anomaly_score_logs')
    op.drop_index(op.f('ix_anomaly_score_logs_id'), table_name='anomaly_score_logs')
    op.drop_index(op.f('ix_anomaly_score_logs_created_at'), table_name='anomaly_score_logs')
    op.drop_index(op.f('ix_anomaly_score_logs_anomaly_job_id'), table_name='anomaly_score_logs')
    op.drop_table('anomaly_score_logs')
    # ### end Alembic commands ###
